name: flutter_data_kit_example
description: Fake PagedSource + PagedList notifier demo for flutter_data_kit.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_data_kit: ^1.0.0
  flutter_riverpod: ^3.4.2
  lemsa_core_kit:
    path: ../../lemsa_core_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
